# !!! -------------------------------------------- !!!
# !!! Do not change config.toml as it is generated !!!
# !!! Any edits should go into config-base.toml    !!!
# !!! -------------------------------------------- !!!
[editor]
color-modes = true
middle-click-paste = false
bufferline = "always"

[editor.indent-guides]
render = true
character = "⏐"
skip-levels = 1

[editor.soft-wrap]
enable = true

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "spacer",
  "separator",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",

]
center = []
right = [
  "diagnostics",
  "workspace-diagnostics",
  "position",
  "total-line-numbers",
  "position-percentage",
  "file-encoding",
  "file-line-ending",
  "file-type",
  "register",
]
separator = "│"


[editor.cursor-shape]
insert = "bar"

[keys.normal.space.b]
b = "buffer_picker"
c = ":buffer-close"
r = ":reload"
R = ":reload-all"
w = ":write"
x = ":write-buffer-close"
