[[language]]
name = "go"
scope = "source.go"
file-types = ["go"]
roots = ["go.work", "go.mod"]
auto-format = true
language-servers = ["gopls"]

[language-server.gopls]
command = "gopls"
args = []
config = { "staticcheck" = true, "usePlaceholders" = true, "analyses" = { "unusedparams" = true } }
