#!/usr/bin/env bash

set -e
set -x

cd "$(git rev-parse --show-toplevel)"
find .git -type f -regextype egrep -regex '.*(commit-graph.*lock|tmp_graph.*)' -exec rm {} +
git gc --force --aggressive --prune=now
git commit-graph write
