#!/bin/bash

# TODO: packed-refs are not handled

git_root=$(git rev-parse --show-toplevel)

# List branches in a tree format
# The 'tree' command lists files in a tree structure, and '-P' excludes any pattern
tree -P '*' -I 'packed-refs' --noreport "$git_root"/.git/refs/heads | sed -E "s|($(git symbolic-ref --short HEAD))|\\1 *|"
