#!/usr/bin/env bash

_bkup() {
	if [[ ! -d "$1" ]] && [[ ! -L "$1" ]]; then
		return
	fi
	log "backup up <<< $1"
	prefix="$1".bkup
	counter=1
	while true; do
		target="$prefix"_"$counter"
		if [ ! -e "$target" ]; then
			log "backup to >>> $target"
			mv -- "$1" "$target"
			break
		fi
		counter=$((counter + 1))
	done
}
