#!/usr/bin/env bash

export PATH="$HOME/.local/bin:$PATH"

# usage: switch-theme [dark|light]
reload-kitty() {
	cp ~/.config/kitty/"$1".conf ~/.config/kitty/current-theme.conf
	kill -sigusr1 $(pgrep -a kitty) 2>/dev/null
}

reload-fish() {
	fish -c "fish_toggle_color $1"
}

reload-git() {
	cp ~/.config/git/delta_theme_"$1" ~/.config/git/delta_theme
}

reload-neovim() { # only works for neovim 0.9+
	find /var/folders -type s -name 'nvim*' -print0 2>/dev/null |
		xargs -0 -I{} nvim --server {} --remote-send "<cmd>set background=$1<cr>"
}

reload-helix() {
	# Generate config.toml by combining theme + base config
	cat ~/.config/helix/theme_"$1".toml ~/.config/helix/config-base.toml > ~/.config/helix/config.toml

	# Reload running Helix instances by sending USR1 signal
	pkill -USR1 hx 2>/dev/null
}

switch-theme() {
	if [[ "$1" = 'dark' || "$1" = 'light' ]]; then
		# Run all reloads in parallel for faster theme switching
		reload-fish "$@" &
		reload-git "$@" &
		reload-neovim "$@" &
		reload-helix "$@" &
		wait
	fi
}

switch-theme "$@"
