#!/usr/bin/env bash

# usage: symlink to from
symlink() {
	if readlink "$2" | grep -q $(realpath "$1"); then
		log "symlink from $2 to $1 already established"
		return 0
	fi

	log "symlink from $2 to $1"
	_bkup "$2"
	mkdir -p "$(dirname "$2")"
	ln -s $(pwd)/"$1" "$2"
}